"""
Módulo de reconstrucción de petroglifos deteriorados.

Pipeline:
  1. Preprocesamiento + predicción TTA — modelo Keras (segmentar_petroglifo)
  2. Detección de zonas dañadas (probabilidad intermedia cerca de zonas seguras)
  3. Inpainting generativo con LaMa GAN sobre zonas dañadas
  4. Re-segmentación de la imagen reconstruida para refinar la máscara
  5. Renderizado fotorrealista sobre fondo pétreo (render_petroglyph)
"""
# Generated by GitHub Copilot
from __future__ import annotations

import cv2
import numpy as np
import PIL.Image
import PIL.ImageFilter
import os
from pathlib import Path

from segmentar_petroglifo import (
    IMG_SIZE,
    DEFAULT_THRESHOLD,
    DEFAULT_MIN_AREA,
    preprocess,
    predict_tta,
    select_best_mask,
    adelgazar_mascara,
    render_petroglyph,
    choose_background,
    evaluate_mask,
)

# ---------------------------------------------------------------------------
# Parámetros públicos del módulo
# ---------------------------------------------------------------------------
DEFAULT_DAMAGE_LOW_THRESH: float = 0.10
DEFAULT_DAMAGE_HIGH_THRESH: float = 0.45
DEFAULT_DAMAGE_DILATION_PX: int = 30
DEFAULT_COMPOSE_BLUR_RADIUS: float = 3.0


# ---------------------------------------------------------------------------
# Carga del modelo LaMa
# ---------------------------------------------------------------------------

# Ruta por defecto a los pesos fine-tuneados (relativa a la raíz del proyecto)
DEFAULT_LAMA_MODEL_PATH: str = "modelo/lama_petroglifos.pt"


def load_lama_model(model_path: str | None = DEFAULT_LAMA_MODEL_PATH) -> object:
    """
    Carga el modelo LaMa para inpainting con pérdida adversarial.

    Prioridad de carga:
      1. Pesos fine-tuneados en ``model_path`` (``modelo/lama_petroglifos.pt``)
         — generados tras el fine-tuning sobre el corpus de petroglifos.
      2. Pesos genéricos preentrenados descargados automáticamente (~200 MB)
         — fallback si el archivo fine-tuneado no existe todavía.

    Parameters
    ----------
    model_path : str | None
        Ruta al archivo ``.pt`` con pesos fine-tuneados.
        Pasa ``None`` para forzar el uso de pesos genéricos.

    Returns
    -------
    SimpleLama
        Instancia del modelo LaMa lista para inferencia.

    Raises
    ------
    ImportError
        Si ``simple-lama-inpainting`` no está instalado.
    """
    try:
        from simple_lama_inpainting import SimpleLama  # type: ignore[import-not-found]
    except ImportError as exc:
        raise ImportError(
            "simple-lama-inpainting no está instalado. "
            "Ejecuta: pip install simple-lama-inpainting"
        ) from exc

    fine_tuned_path = Path(model_path) if model_path else None

    if fine_tuned_path is not None and fine_tuned_path.is_file():
        print(f"  → Usando pesos fine-tuneados: {fine_tuned_path}")
        os.environ["LAMA_MODEL"] = str(fine_tuned_path)
    else:
        print("  → Pesos fine-tuneados no encontrados, usando pesos genéricos preentrenados.")
        os.environ.pop("LAMA_MODEL", None)

    return SimpleLama()


# ---------------------------------------------------------------------------
# Inpainting con LaMa
# ---------------------------------------------------------------------------

def _lama_inpaint(
    lama_model,
    img_bgr: np.ndarray,
    damage_mask: np.ndarray,
) -> np.ndarray:
    """
    Aplica inpainting LaMa sobre las zonas marcadas en ``damage_mask``.

    Parameters
    ----------
    lama_model : SimpleLama
        Instancia del modelo LaMa cargado.
    img_bgr : np.ndarray
        Imagen BGR uint8 de forma (H, W, 3).
    damage_mask : np.ndarray
        Máscara binaria uint8 (255 = zona a reconstruir) de forma (H, W).

    Returns
    -------
    np.ndarray
        Imagen BGR uint8 con las zonas dañadas reconstruidas por LaMa.
    """
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    img_pil = PIL.Image.fromarray(img_rgb)
    # LaMa espera la máscara en modo 'L' con blanco = zona a rellenar
    mask_pil = PIL.Image.fromarray(damage_mask).convert("L")

    result_pil = lama_model(img_pil, mask_pil)
    result_rgb = np.array(result_pil.convert("RGB"))
    return cv2.cvtColor(result_rgb, cv2.COLOR_RGB2BGR)


def soft_compose_with_mask(
    base_rgb: np.ndarray,
    overlay_rgb: np.ndarray,
    mask: np.ndarray,
    blur_radius: float = DEFAULT_COMPOSE_BLUR_RADIUS,
) -> np.ndarray:
    """
    Mezcla suavemente ``overlay_rgb`` sobre ``base_rgb`` usando ``mask``.

    La máscara se difumina con Gaussian blur para evitar bordes duros en la
    transición entre la zona reconstruida y la imagen original.
    """
    if base_rgb.shape != overlay_rgb.shape:
        raise ValueError("base_rgb y overlay_rgb deben tener la misma forma")
    if mask.ndim != 2:
        raise ValueError("mask debe tener 2 dimensiones")

    mask_pil = PIL.Image.fromarray(mask.astype(np.uint8)).convert("L")
    alpha = mask_pil.filter(PIL.ImageFilter.GaussianBlur(radius=blur_radius))
    alpha_np = np.array(alpha, dtype=np.float32) / 255.0
    alpha_np = alpha_np[..., None]

    base_np = base_rgb.astype(np.float32)
    overlay_np = overlay_rgb.astype(np.float32)
    composed = base_np * (1.0 - alpha_np) + overlay_np * alpha_np
    return np.clip(composed, 0, 255).astype(np.uint8)


# ---------------------------------------------------------------------------
# Detección de zonas dañadas
# ---------------------------------------------------------------------------

def detect_damage_region(
    probability: np.ndarray,
    low_thresh: float = DEFAULT_DAMAGE_LOW_THRESH,
    high_thresh: float = DEFAULT_DAMAGE_HIGH_THRESH,
    dilation_px: int = DEFAULT_DAMAGE_DILATION_PX,
) -> np.ndarray:
    """
    Identifica zonas presumiblemente dañadas en la imagen del petroglifo.

    Las zonas dañadas se definen como píxeles cuya probabilidad predicha está
    en el rango [low_thresh, high_thresh) y que son adyacentes (dentro de
    ``dilation_px`` píxeles) a zonas de alta confianza (>= high_thresh).
    Este criterio captura surcos erosionados o parcialmente cubiertos que el
    modelo no pudo segmentar con certeza, sin marcar como dañadas las zonas
    que simplemente no contienen petroglifo.

    Parameters
    ----------
    probability : np.ndarray
        Mapa de probabilidad de forma (H, W) en rango [0, 1].
    low_thresh : float
        Umbral mínimo de probabilidad para considerar un píxel como incierto.
    high_thresh : float
        Umbral a partir del cual un píxel se considera petroglifo confirmado.
    dilation_px : int
        Radio de dilatación para buscar vecindad con zonas de alta confianza.

    Returns
    -------
    np.ndarray
        Máscara binaria uint8 (255 = zona dañada, 0 = zona sana) con forma (H, W).

    Security note
    -------------
    Solo opera sobre arrays numpy producidos internamente; no acepta rutas ni
    contenido externo sin validación previa en la capa de servicio.
    """
    high_conf = (probability >= high_thresh).astype(np.uint8)
    uncertain = (
        (probability >= low_thresh) & (probability < high_thresh)
    ).astype(np.uint8)

    kernel_size = max(3, dilation_px | 1)  # Asegurar impar >= 3
    kernel = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE, (kernel_size, kernel_size)
    )
    dilated_high = cv2.dilate(high_conf, kernel, iterations=1)

    # Solo marcar como dañado lo que es incierto Y cercano al petroglifo
    damage_mask = (uncertain & dilated_high).astype(np.uint8) * 255
    return damage_mask


# ---------------------------------------------------------------------------
# Reconstrucción completa
# ---------------------------------------------------------------------------

def reconstruct_petroglyph(
    seg_model,
    lama_model,
    img_bgr: np.ndarray,
    threshold: float = DEFAULT_THRESHOLD,
    min_area: int = DEFAULT_MIN_AREA,
    background_path: Path | None = None,
    damage_low_thresh: float = DEFAULT_DAMAGE_LOW_THRESH,
    damage_high_thresh: float = DEFAULT_DAMAGE_HIGH_THRESH,
    damage_dilation_px: int = DEFAULT_DAMAGE_DILATION_PX,
    manual_damage_mask: np.ndarray | None = None,
) -> dict[str, object]:
    """
    Reconstruye un petroglifo deteriorado usando Keras + LaMa GAN.

    Pasos:
      1. Redimensiona y aplica CLAHE para mejorar contraste.
      2. Modelo Keras (U-Net): predicción TTA → mapa de probabilidad.
      3. Selecciona la mejor máscara de segmentación.
      4. Detecta zonas dañadas (erosión, fracturas, liquen).
      5. LaMa GAN: inpainting generativo en zonas dañadas.
      6. Modelo Keras: re-segmentación de la imagen reconstruida.
      7. Combina ambos mapas de probabilidad para máscara final refinada.
      8. Renderiza el petroglifo sobre un fondo pétreo.

    Parameters
    ----------
    seg_model : keras.Model
        Modelo Keras de segmentación (U-Net) cargado.
    lama_model : SimpleLama
        Modelo LaMa de inpainting generativo cargado.
    img_bgr : np.ndarray
        Imagen BGR de entrada (cualquier tamaño; se redimensiona internamente).
    threshold : float
        Umbral inicial de binarización para la máscara.
    min_area : int
        Área mínima de componentes en la máscara.
    background_path : Path | None
        Ruta opcional a una imagen de fondo. Si es None se elige aleatoriamente.
    damage_low_thresh : float
        Umbral bajo para detección de zonas dañadas.
    damage_high_thresh : float
        Umbral alto (zona confirmada como petroglifo).
    damage_dilation_px : int
        Radio de dilatación para detección de vecindad de daño.
    manual_damage_mask : np.ndarray | None
        Máscara binaria opcional (255 = zona a reconstruir). Si se proporciona,
        se usa en lugar de la detección automática de daño.

    Returns
    -------
    dict con claves:
        - ``original_rgb``          : imagen original redimensionada (RGB, uint8)
        - ``inpainted_rgb``         : imagen tras inpainting LaMa (RGB, uint8)
        - ``composed_rgb``          : mezcla suave entre original e inpainted
        - ``probability``           : mapa de probabilidad Keras original (H×W)
        - ``probability_merged``    : mapa combinado post-LaMa (H×W)
        - ``filled_mask``           : máscara binaria final del petroglifo (uint8)
        - ``damage_mask``           : máscara de zonas dañadas detectadas (uint8)
        - ``line_mask``             : esqueleto/contorno del petroglifo (uint8)
        - ``rendered_rgb``          : reconstrucción final sobre fondo (RGB, uint8)
        - ``background_name``       : nombre del fondo utilizado
        - ``metrics``               : dict de métricas de la máscara
        - ``selected_threshold``    : umbral seleccionado automáticamente
        - ``selected_strategy``     : estrategia ("raw" | "refined")
        - ``damage_pixel_count``    : número de píxeles reconstruidos por LaMa
    """
    # 1. Preprocesamiento y predicción con modelo Keras (U-Net)
    img_resized = cv2.resize(img_bgr, (IMG_SIZE, IMG_SIZE), interpolation=cv2.INTER_AREA)
    img_pre = preprocess(img_bgr)
    probability = predict_tta(seg_model, img_pre)

    # 2. Mejor máscara de segmentación inicial
    selected = select_best_mask(probability, threshold, min_area)
    filled_mask: np.ndarray = selected["mask"]  # type: ignore[assignment]
    metrics: dict = selected["metrics"]  # type: ignore[assignment]

    # 3. Detección de zonas dañadas (surcos erosionados, líquenes, fracturas)
    if manual_damage_mask is not None:
        damage_mask = manual_damage_mask.astype(np.uint8)
    else:
        damage_mask = detect_damage_region(
            probability,
            low_thresh=damage_low_thresh,
            high_thresh=damage_high_thresh,
            dilation_px=damage_dilation_px,
        )
    damage_pixel_count = int((damage_mask > 0).sum())

    # 4. LaMa GAN: inpainting generativo en zonas dañadas
    if damage_pixel_count > 0:
        inpainted_bgr = _lama_inpaint(lama_model, img_resized, damage_mask)
    else:
        inpainted_bgr = img_resized.copy()

    # 4.1 Composición suave guiada por la máscara para conservar el contexto
    original_rgb = cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB)
    inpainted_rgb = cv2.cvtColor(inpainted_bgr, cv2.COLOR_BGR2RGB)
    composed_rgb = soft_compose_with_mask(
        original_rgb,
        inpainted_rgb,
        damage_mask,
    )

    # 5. Re-segmentación Keras sobre imagen reconstruida por LaMa
    #    → combina ambos mapas de probabilidad para refinar la máscara final
    if damage_pixel_count > 0:
        img_pre_inpainted = preprocess(inpainted_bgr)
        prob_inpainted = predict_tta(seg_model, img_pre_inpainted)
        # Media ponderada: más peso a la probabilidad post-LaMa donde hay daño
        weight_original = np.where(damage_mask > 0, 0.35, 0.65)
        weight_inpainted = 1.0 - weight_original
        probability_merged = (
            probability * weight_original + prob_inpainted * weight_inpainted
        )
        selected_merged = select_best_mask(probability_merged, threshold, min_area)
        final_mask: np.ndarray = selected_merged["mask"]  # type: ignore[assignment]
    else:
        probability_merged = probability
        final_mask = filled_mask

    # 6. Línea esqueleto del petroglifo reconstruido
    line_mask = adelgazar_mascara(final_mask)

    # 7. Renderizado fotorrealista
    background_rgb, background_name = choose_background(background_path)
    rendered_rgb = render_petroglyph(background_rgb, final_mask)

    return {
        "original_rgb": original_rgb,
        "inpainted_rgb": inpainted_rgb,
        "composed_rgb": composed_rgb,
        "probability": probability,
        "probability_merged": probability_merged,
        "filled_mask": final_mask,
        "damage_mask": damage_mask,
        "line_mask": line_mask,
        "rendered_rgb": rendered_rgb,
        "background_name": str(background_name),
        "metrics": metrics,
        "selected_threshold": float(selected["threshold"]),  # type: ignore[arg-type]
        "selected_strategy": str(selected["strategy"]),
        "damage_pixel_count": damage_pixel_count,
    }
