# Generated by GitHub Copilot
import base64
import io
import warnings
from pathlib import Path

import PIL.Image
import numpy as np
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response

warnings.filterwarnings("ignore")

app = FastAPI()

origins = [
    "http://localhost:5173",
    "http://localhost:5174",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

SEGMENTATION_MODEL = None
LAMA_MODEL = None
PYTORCH_DAMAGE_MODEL = None
PETROGLYPH_IMPORT_ERROR = None
petroglyph = None
reconstruir = None
RECONSTRUCTION_IMPORT_ERROR = None
damage_segmentation = None
PYTORCH_SEGMENTATION_IMPORT_ERROR = None

DEFAULT_SEGMENTATION_THRESHOLD = 0.5
DEFAULT_SEGMENTATION_MIN_AREA = 150
DEFAULT_SEGMENTATION_LINE_WIDTH = 2
DEFAULT_DAMAGE_SEGMENTATION_THRESHOLD = 0.20
DEFAULT_DAMAGE_SEGMENTATION_MIN_AREA = 30
VISUAL_ASSISTED_OUTPUT_DIR = Path(__file__).resolve().parent / "outputs"

try:
    import segmentar_petroglifo as petroglyph  # type: ignore[import-not-found]
except Exception as exc:
    PETROGLYPH_IMPORT_ERROR = exc
    petroglyph = None
else:
    DEFAULT_SEGMENTATION_THRESHOLD = petroglyph.DEFAULT_THRESHOLD
    DEFAULT_SEGMENTATION_MIN_AREA = petroglyph.DEFAULT_MIN_AREA
    DEFAULT_SEGMENTATION_LINE_WIDTH = petroglyph.DEFAULT_LINE_WIDTH

try:
    import reconstruir_petroglifo as reconstruir  # type: ignore[import-not-found]
except Exception as exc:
    RECONSTRUCTION_IMPORT_ERROR = exc
    reconstruir = None

try:
    import segmentar_danos_pytorch as damage_segmentation  # type: ignore[import-not-found]
except Exception as exc:
    PYTORCH_SEGMENTATION_IMPORT_ERROR = exc
    damage_segmentation = None
else:
    DEFAULT_DAMAGE_SEGMENTATION_THRESHOLD = damage_segmentation.DEFAULT_THRESHOLD
    DEFAULT_DAMAGE_SEGMENTATION_MIN_AREA = damage_segmentation.DEFAULT_MIN_AREA

def pil_to_b64(pil_img: PIL.Image.Image) -> str:
    buf = io.BytesIO()
    pil_img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode()


def array_to_b64(image_array: np.ndarray) -> str:
    pil_img = PIL.Image.fromarray(image_array)
    return pil_to_b64(pil_img)


def grayscale_to_b64(image_array: np.ndarray) -> str:
    pil_img = PIL.Image.fromarray(image_array.astype(np.uint8), mode="L")
    return pil_to_b64(pil_img)


def array_to_png_bytes(image_array: np.ndarray) -> bytes:
    pil_img = PIL.Image.fromarray(image_array)
    buf = io.BytesIO()
    pil_img.save(buf, format="PNG")
    return buf.getvalue()


def build_segmentation_status(metrics: dict, strategy: str) -> str:
    warnings = set(metrics.get("warnings", []))
    if "mask_empty" in warnings or "mask_too_small" in warnings:
        return "weak_segmentation"
    if "mask_too_large" in warnings:
        return "oversegmented"
    if strategy == "refined":
        return "refined_mask"
    return "ok"


def ensure_pytorch_damage_model():
    global PYTORCH_DAMAGE_MODEL

    if damage_segmentation is None:
        raise RuntimeError(
            "La segmentacion PyTorch no esta disponible porque faltan dependencias "
            f"({PYTORCH_SEGMENTATION_IMPORT_ERROR})."
        )

    if PYTORCH_DAMAGE_MODEL is None:
        PYTORCH_DAMAGE_MODEL, pytorch_device = damage_segmentation.load_model(
            damage_segmentation.MODEL_PATH
        )
        print(f"Modelo PyTorch cargado bajo demanda en {pytorch_device}.")

    return PYTORCH_DAMAGE_MODEL, next(PYTORCH_DAMAGE_MODEL.parameters()).device


def predict_pytorch_damage_mask(
    img_bgr: np.ndarray,
    threshold: float = DEFAULT_DAMAGE_SEGMENTATION_THRESHOLD,
    min_area: int = DEFAULT_DAMAGE_SEGMENTATION_MIN_AREA,
    aggressive: bool = False,
) -> tuple[np.ndarray, np.ndarray]:
    model, device = ensure_pytorch_damage_model()
    return damage_segmentation.predict_mask(
        model=model,
        img_bgr=img_bgr,
        device=device,
        threshold=threshold,
        min_area=min_area,
        aggressive=aggressive,
    )


@app.on_event("startup")
async def startup_event():
    global SEGMENTATION_MODEL, LAMA_MODEL, PYTORCH_DAMAGE_MODEL

    if petroglyph is None:
        print(f"Segmentacion deshabilitada: {PETROGLYPH_IMPORT_ERROR}")
        return

    # --- Modelo Keras de segmentación (U-Net) ---
    segmentation_model_path = str(petroglyph.MODEL_PATH)
    print(f"Cargando modelo Keras (segmentación) desde {segmentation_model_path} ...")
    try:
        SEGMENTATION_MODEL = petroglyph.load_model(
            segmentation_model_path,
            custom_objects={
                "bce_dice_loss": petroglyph.bce_dice_loss,
                "dice_coefficient": petroglyph.dice_coefficient,
                "iou_score": petroglyph.iou_score,
            },
        )
        print("Modelo Keras cargado correctamente.")
    except Exception as e:
        print(f"Error cargando modelo Keras: {e}")

    # --- Modelo LaMa (inpainting con pérdida adversarial) ---
    if reconstruir is None:
        print(f"LaMa deshabilitado: {RECONSTRUCTION_IMPORT_ERROR}")
        return

    lama_model_path = reconstruir.DEFAULT_LAMA_MODEL_PATH
    print(f"Cargando modelo LaMa desde '{lama_model_path}' (fallback: pesos genéricos) ...")
    try:
        LAMA_MODEL = reconstruir.load_lama_model(model_path=lama_model_path)
        print("Modelo LaMa cargado correctamente.")
    except Exception as e:
        print(f"Error cargando modelo LaMa: {e}")

    if damage_segmentation is None:
        print(f"Segmentacion PyTorch deshabilitada: {PYTORCH_SEGMENTATION_IMPORT_ERROR}")
        return

    pytorch_model_path = str(damage_segmentation.MODEL_PATH)
    print(f"Cargando modelo PyTorch de segmentacion desde {pytorch_model_path} ...")
    try:
        PYTORCH_DAMAGE_MODEL, pytorch_device = damage_segmentation.load_model(pytorch_model_path)
        print(f"Modelo PyTorch cargado correctamente en {pytorch_device}.")
    except Exception as e:
        print(f"Error cargando modelo PyTorch: {e}")


@app.post("/segmentPetroglyph")
async def segment_petroglyph(
    file: UploadFile = File(...),
    threshold: float = Form(DEFAULT_SEGMENTATION_THRESHOLD),
    min_area: int = Form(DEFAULT_SEGMENTATION_MIN_AREA),
    line_width: int = Form(DEFAULT_SEGMENTATION_LINE_WIDTH),
    include_previews: bool = Form(True),
):
    global SEGMENTATION_MODEL

    if petroglyph is None:
        raise HTTPException(
            status_code=503,
            detail=(
                "La segmentacion no esta disponible porque faltan dependencias del modelo "
                f"({PETROGLYPH_IMPORT_ERROR})."
            ),
        )

    if SEGMENTATION_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo de segmentacion no cargado")

    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Debes enviar un archivo de imagen valido")

    content = await file.read()
    if not content:
        raise HTTPException(status_code=400, detail="La imagen enviada esta vacia")

    np_buffer = np.frombuffer(content, np.uint8)
    img_bgr = petroglyph.cv2.imdecode(np_buffer, petroglyph.cv2.IMREAD_COLOR)
    if img_bgr is None:
        raise HTTPException(status_code=400, detail="No se pudo leer la imagen enviada")

    img_pre = petroglyph.preprocess(img_bgr)
    probability = petroglyph.predict_tta(SEGMENTATION_MODEL, img_pre)

    selected_mask = petroglyph.select_best_mask(probability, threshold, min_area)
    filled_mask = selected_mask["mask"]
    line_mask = petroglyph.adelgazar_mascara(filled_mask, grosor=line_width)
    metrics = selected_mask["metrics"]

    original_rgb = petroglyph.cv2.cvtColor(
        petroglyph.cv2.resize(img_bgr, (petroglyph.IMG_SIZE, petroglyph.IMG_SIZE), interpolation=petroglyph.cv2.INTER_AREA),
        petroglyph.cv2.COLOR_BGR2RGB,
    )
    background_rgb, background_name = petroglyph.choose_background(None)
    rendered_rgb = petroglyph.render_petroglyph(background_rgb, filled_mask)

    area_percent = float(metrics["area_percent"])
    segmentation_status = build_segmentation_status(metrics, str(selected_mask["strategy"]))

    response = {
        "filename": file.filename,
        "background_name": background_name,
        "threshold": threshold,
        "min_area": min_area,
        "line_width": line_width,
        "area_percent": round(area_percent, 2),
        "segmentation_status": segmentation_status,
        "selected_threshold": float(selected_mask["threshold"]),
        "selected_strategy": str(selected_mask["strategy"]),
        "validation_score": round(float(metrics["score"]), 2),
        "validation_warnings": list(metrics["warnings"]),
        "component_count": int(metrics["component_count"]),
        "size": {
            "width": petroglyph.IMG_SIZE,
            "height": petroglyph.IMG_SIZE,
        },
        "result_image": array_to_b64(rendered_rgb),
        "background_image": array_to_b64(background_rgb),
        "mask_image": grayscale_to_b64(filled_mask),
    }

    if include_previews:
        probability_img = np.clip(probability * 255.0, 0, 255).astype(np.uint8)
        response.update(
            {
                "original_image": array_to_b64(original_rgb),
                "probability_image": grayscale_to_b64(probability_img),
                "line_image": grayscale_to_b64(line_mask),
            }
        )

    return response


@app.post("/segmentDamagePytorch")
async def segment_damage_pytorch(
    file: UploadFile = File(...),
    threshold: float = Form(DEFAULT_DAMAGE_SEGMENTATION_THRESHOLD),
    min_area: int = Form(DEFAULT_DAMAGE_SEGMENTATION_MIN_AREA),
    aggressive: bool = Form(False),
    save_png: bool = Form(True),
):
    global PYTORCH_DAMAGE_MODEL

    if damage_segmentation is None:
        raise HTTPException(
            status_code=503,
            detail=(
                "La segmentacion PyTorch no esta disponible porque faltan dependencias "
                f"({PYTORCH_SEGMENTATION_IMPORT_ERROR})."
            ),
        )

    if not (0.0 < threshold < 1.0):
        raise HTTPException(status_code=400, detail="threshold debe estar en (0, 1)")
    if not (0 <= min_area <= 50000):
        raise HTTPException(status_code=400, detail="min_area debe estar entre 0 y 50000")

    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Debes enviar un archivo de imagen valido")

    content = await file.read()
    if not content:
        raise HTTPException(status_code=400, detail="La imagen enviada esta vacia")

    np_buffer = np.frombuffer(content, np.uint8)
    img_bgr = petroglyph.cv2.imdecode(np_buffer, petroglyph.cv2.IMREAD_COLOR) if petroglyph else None
    if img_bgr is None:
        raise HTTPException(status_code=400, detail="No se pudo leer la imagen enviada")

    try:
        probability, mask = predict_pytorch_damage_mask(
            img_bgr=img_bgr,
            threshold=threshold,
            min_area=min_area,
            aggressive=aggressive,
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"No se pudo ejecutar la segmentacion PyTorch: {exc}") from exc

    mask_path = None
    if save_png:
        from pathlib import Path

        output_dir = Path(__file__).resolve().parent / "outputs"
        output_dir.mkdir(parents=True, exist_ok=True)
        mask_path = damage_segmentation.save_mask_png(
            mask,
            output_dir / f"{Path(file.filename or 'mask').stem}_mascara.png",
        )

    probability_img = np.clip(probability * 255.0, 0, 255).astype(np.uint8)

    return {
        "filename": file.filename,
        "threshold": float(threshold),
        "min_area": int(min_area),
        "aggressive": bool(aggressive),
        "mask_path": str(mask_path) if mask_path else None,
        "mask_image": grayscale_to_b64(mask),
        "probability_image": grayscale_to_b64(probability_img),
    }


# ---------------------------------------------------------------------------
# Endpoints de reconstrucción
# Compatible con el agente A5 del sistema multiagente BackendPetroglifos
# ---------------------------------------------------------------------------

@app.post(
    "/reconstruct",
    summary="Reconstrucción de petroglifo (salida imagen PNG)",
    description=(
        "Recibe una imagen de un petroglifo deteriorado y devuelve la imagen "
        "reconstruida como PNG binario. "
        "Compatible con el agente A5 del sistema multiagente BackendPetroglifos "
        "(settings.gan_api_url)."
    ),
    response_class=Response,
)
async def reconstruct_petroglyph(
    image: UploadFile = File(...),
    mask: UploadFile | None = File(None),
    threshold: float = Form(DEFAULT_SEGMENTATION_THRESHOLD),
    min_area: int = Form(DEFAULT_SEGMENTATION_MIN_AREA),
):
    """
    Pipeline de reconstrucción Keras + LaMa:
    1. Modelo Keras: segmentación TTA → mapa de probabilidad.
    2. Detección de surcos erosionados / zonas dañadas.
    3. LaMa GAN: inpainting generativo en zonas dañadas.
    4. Modelo Keras: re-segmentación post-inpainting.
    5. Renderizado sobre fondo pétreo con efecto de bajo relieve.

    Devuelve la imagen PNG de la reconstrucción como bytes crudos.
    Compatible con el agente A5 (settings.gan_api_url).

    Security note: threshold y min_area se validan contra rangos seguros.
    """
    global SEGMENTATION_MODEL, LAMA_MODEL

    if not (0.0 < threshold < 1.0):
        raise HTTPException(status_code=400, detail="threshold debe estar en (0, 1)")
    if not (0 <= min_area <= 50000):
        raise HTTPException(status_code=400, detail="min_area debe estar entre 0 y 50000")

    if reconstruir is None:
        raise HTTPException(
            status_code=503,
            detail=f"Reconstruccion no disponible: {RECONSTRUCTION_IMPORT_ERROR}",
        )
    if SEGMENTATION_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo Keras no cargado")
    if LAMA_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo LaMa no cargado")
    if not image.content_type or not image.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Debes enviar un archivo de imagen valido")
    if mask is not None and (not mask.content_type or not mask.content_type.startswith("image/")):
        raise HTTPException(status_code=400, detail="La mascara debe ser un archivo de imagen valido")

    content = await image.read()
    if not content:
        raise HTTPException(status_code=400, detail="La imagen enviada esta vacia")

    np_buffer = np.frombuffer(content, np.uint8)
    img_bgr = petroglyph.cv2.imdecode(np_buffer, petroglyph.cv2.IMREAD_COLOR)
    if img_bgr is None:
        raise HTTPException(status_code=400, detail="No se pudo leer la imagen enviada")
    manual_damage_mask = None
    if mask is not None:
        mask_content = await mask.read()
        if not mask_content:
            raise HTTPException(status_code=400, detail="La mascara enviada esta vacia")
        mask_buffer = np.frombuffer(mask_content, np.uint8)
        mask_img = petroglyph.cv2.imdecode(mask_buffer, petroglyph.cv2.IMREAD_GRAYSCALE)
        if mask_img is None:
            raise HTTPException(status_code=400, detail="No se pudo leer la mascara enviada")
        mask_img = petroglyph.cv2.resize(
            mask_img,
            (petroglyph.IMG_SIZE, petroglyph.IMG_SIZE),
            interpolation=petroglyph.cv2.INTER_NEAREST,
        )
        manual_damage_mask = np.where(mask_img > 127, 255, 0).astype(np.uint8)
    else:
        try:
            _, manual_damage_mask = predict_pytorch_damage_mask(
                img_bgr=img_bgr,
                threshold=DEFAULT_DAMAGE_SEGMENTATION_THRESHOLD,
                min_area=DEFAULT_DAMAGE_SEGMENTATION_MIN_AREA,
                aggressive=False,
            )
        except Exception as exc:
            raise HTTPException(status_code=500, detail=f"No se pudo generar la mascara PyTorch: {exc}") from exc

    result = reconstruir.reconstruct_petroglyph(
        SEGMENTATION_MODEL,
        LAMA_MODEL,
        img_bgr,
        threshold=threshold,
        min_area=min_area,
        manual_damage_mask=manual_damage_mask,
    )

    return Response(content=array_to_png_bytes(result["figure_fused_rgb"]), media_type="image/png")


@app.post(
    "/reconstructFull",
    summary="Reconstrucción de petroglifo (salida JSON con todas las etapas)",
    description=(
        "Igual que /reconstruct pero devuelve un JSON con imágenes codificadas en "
        "base-64 para cada etapa del pipeline (original, inpainting, máscara de "
        "daño, máscara final, probabilidad y resultado)."
    ),
)
async def reconstruct_petroglyph_full(
    file: UploadFile = File(...),
    mask: UploadFile | None = File(None),
    threshold: float = Form(DEFAULT_SEGMENTATION_THRESHOLD),
    min_area: int = Form(DEFAULT_SEGMENTATION_MIN_AREA),
    line_width: int = Form(DEFAULT_SEGMENTATION_LINE_WIDTH),
    include_previews: bool = Form(True),
):
    """
    Devuelve todas las etapas del pipeline Keras + LaMa en base64.

    Campos del JSON:
    - ``result_image``             : imagen reparada principal (composición suave)
    - ``rendered_image``           : reconstrucción final sobre fondo pétreo
    - ``composed_image``           : composición suave original + LaMa
    - ``inpainted_image``          : imagen tras inpainting LaMa
    - ``mask_image``               : máscara binaria final del petroglifo
    - ``damage_mask_image``        : máscara de zonas reconstruidas por LaMa
    - ``background_image``         : fondo pétreo utilizado
    - ``original_image``           : imagen original (si include_previews)
    - ``probability_image``        : mapa de probabilidad Keras (si include_previews)
    - ``probability_merged_image`` : mapa combinado post-LaMa (si include_previews)
    - ``line_image``               : esqueleto del petroglifo (si include_previews)
    - Métricas, umbrales y estadísticas del daño detectado.

    Security note: threshold y min_area se validan contra rangos seguros.
    """
    global SEGMENTATION_MODEL, LAMA_MODEL

    if not (0.0 < threshold < 1.0):
        raise HTTPException(status_code=400, detail="threshold debe estar en (0, 1)")
    if not (0 <= min_area <= 50000):
        raise HTTPException(status_code=400, detail="min_area debe estar entre 0 y 50000")

    if reconstruir is None:
        raise HTTPException(
            status_code=503,
            detail=f"Reconstruccion no disponible: {RECONSTRUCTION_IMPORT_ERROR}",
        )
    if SEGMENTATION_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo Keras no cargado")
    if LAMA_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo LaMa no cargado")
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Debes enviar un archivo de imagen valido")

    content = await file.read()
    if not content:
        raise HTTPException(status_code=400, detail="La imagen enviada esta vacia")

    np_buffer = np.frombuffer(content, np.uint8)
    img_bgr = petroglyph.cv2.imdecode(np_buffer, petroglyph.cv2.IMREAD_COLOR)
    if img_bgr is None:
        raise HTTPException(status_code=400, detail="No se pudo leer la imagen enviada")

    manual_damage_mask = None
    if mask is not None:
        mask_content = await mask.read()
        if not mask_content:
            raise HTTPException(status_code=400, detail="La mascara enviada esta vacia")
        mask_buffer = np.frombuffer(mask_content, np.uint8)
        mask_img = petroglyph.cv2.imdecode(mask_buffer, petroglyph.cv2.IMREAD_GRAYSCALE)
        if mask_img is None:
            raise HTTPException(status_code=400, detail="No se pudo leer la mascara enviada")
        mask_img = petroglyph.cv2.resize(
            mask_img,
            (petroglyph.IMG_SIZE, petroglyph.IMG_SIZE),
            interpolation=petroglyph.cv2.INTER_NEAREST,
        )
        manual_damage_mask = np.where(mask_img > 127, 255, 0).astype(np.uint8)
    else:
        try:
            _, manual_damage_mask = predict_pytorch_damage_mask(
                img_bgr=img_bgr,
                threshold=DEFAULT_DAMAGE_SEGMENTATION_THRESHOLD,
                min_area=DEFAULT_DAMAGE_SEGMENTATION_MIN_AREA,
            )
        except Exception as exc:
            raise HTTPException(status_code=500, detail=f"No se pudo generar la mascara PyTorch: {exc}") from exc

    result = reconstruir.reconstruct_petroglyph(
        SEGMENTATION_MODEL,
        LAMA_MODEL,
        img_bgr,
        threshold=threshold,
        min_area=min_area,
        manual_damage_mask=manual_damage_mask,
    )

    metrics = result["metrics"]
    damage_count = int(result["damage_pixel_count"])
    total_pixels = petroglyph.IMG_SIZE * petroglyph.IMG_SIZE
    damage_percent = round(damage_count / total_pixels * 100.0, 2)

    response: dict = {
        "filename": file.filename,
        "background_name": result["background_name"],
        "threshold": threshold,
        "min_area": min_area,
        "line_width": line_width,
        "area_percent": round(float(metrics["area_percent"]), 2),
        "damage_pixel_count": damage_count,
        "damage_percent": damage_percent,
        "selected_threshold": result["selected_threshold"],
        "selected_strategy": result["selected_strategy"],
        "validation_score": round(float(metrics["score"]), 2),
        "validation_warnings": list(metrics["warnings"]),
        "component_count": int(metrics["component_count"]),
        "size": {
            "width": petroglyph.IMG_SIZE,
            "height": petroglyph.IMG_SIZE,
        },
        "result_image": array_to_b64(result["composed_rgb"]),
        "rendered_image": array_to_b64(result["rendered_rgb"]),
        "composed_image": array_to_b64(result["composed_rgb"]),
        "inpainted_image": array_to_b64(result["inpainted_rgb"]),
        "mask_image": grayscale_to_b64(result["filled_mask"]),
        "damage_mask_image": grayscale_to_b64(result["damage_mask"]),
        "background_image": array_to_b64(
            petroglyph.choose_background(None)[0]
        ),
    }

    if include_previews:
        prob_img = np.clip(result["probability"] * 255.0, 0, 255).astype(np.uint8)
        prob_merged_img = np.clip(
            result["probability_merged"] * 255.0, 0, 255
        ).astype(np.uint8)
        response.update(
            {
                "original_image": array_to_b64(result["original_rgb"]),
                "probability_image": grayscale_to_b64(prob_img),
                "probability_merged_image": grayscale_to_b64(prob_merged_img),
                "line_image": grayscale_to_b64(result["line_mask"]),
            }
        )

    return response


@app.post(
    "/reconstructFullPng",
    summary="Reconstrucción de petroglifo (salida PNG reparada)",
    description=(
        "Igual que /reconstructFull, pero devuelve directamente la imagen reparada "
        "principal como PNG binario."
    ),
    response_class=Response,
)
async def reconstruct_petroglyph_full_png(
    file: UploadFile = File(...),
    mask: UploadFile | None = File(None),
    threshold: float = Form(DEFAULT_SEGMENTATION_THRESHOLD),
    min_area: int = Form(DEFAULT_SEGMENTATION_MIN_AREA),
):
    global SEGMENTATION_MODEL, LAMA_MODEL

    if not (0.0 < threshold < 1.0):
        raise HTTPException(status_code=400, detail="threshold debe estar en (0, 1)")
    if not (0 <= min_area <= 50000):
        raise HTTPException(status_code=400, detail="min_area debe estar entre 0 y 50000")

    if reconstruir is None:
        raise HTTPException(
            status_code=503,
            detail=f"Reconstruccion no disponible: {RECONSTRUCTION_IMPORT_ERROR}",
        )
    if SEGMENTATION_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo Keras no cargado")
    if LAMA_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo LaMa no cargado")
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Debes enviar un archivo de imagen valido")
    if mask is not None and (not mask.content_type or not mask.content_type.startswith("image/")):
        raise HTTPException(status_code=400, detail="La mascara debe ser un archivo de imagen valido")
    if mask is not None and (not mask.content_type or not mask.content_type.startswith("image/")):
        raise HTTPException(status_code=400, detail="La mascara debe ser un archivo de imagen valido")

    content = await file.read()
    if not content:
        raise HTTPException(status_code=400, detail="La imagen enviada esta vacia")

    np_buffer = np.frombuffer(content, np.uint8)
    img_bgr = petroglyph.cv2.imdecode(np_buffer, petroglyph.cv2.IMREAD_COLOR)
    if img_bgr is None:
        raise HTTPException(status_code=400, detail="No se pudo leer la imagen enviada")

    manual_damage_mask = None
    if mask is not None:
        mask_content = await mask.read()
        if not mask_content:
            raise HTTPException(status_code=400, detail="La mascara enviada esta vacia")
        mask_buffer = np.frombuffer(mask_content, np.uint8)
        mask_img = petroglyph.cv2.imdecode(mask_buffer, petroglyph.cv2.IMREAD_GRAYSCALE)
        if mask_img is None:
            raise HTTPException(status_code=400, detail="No se pudo leer la mascara enviada")
        mask_img = petroglyph.cv2.resize(
            mask_img,
            (petroglyph.IMG_SIZE, petroglyph.IMG_SIZE),
            interpolation=petroglyph.cv2.INTER_NEAREST,
        )
        manual_damage_mask = np.where(mask_img > 127, 255, 0).astype(np.uint8)
    else:
        try:
            _, manual_damage_mask = predict_pytorch_damage_mask(
                img_bgr=img_bgr,
                threshold=DEFAULT_DAMAGE_SEGMENTATION_THRESHOLD,
                min_area=DEFAULT_DAMAGE_SEGMENTATION_MIN_AREA,
            )
        except Exception as exc:
            raise HTTPException(status_code=500, detail=f"No se pudo generar la mascara PyTorch: {exc}") from exc

    result = reconstruir.reconstruct_petroglyph(
        SEGMENTATION_MODEL,
        LAMA_MODEL,
        img_bgr,
        threshold=threshold,
        min_area=min_area,
        manual_damage_mask=manual_damage_mask,
    )

    return Response(
        content=array_to_png_bytes(result["composed_rgb"]),
        media_type="image/png",
    )


@app.post("/reconstructVisualAssisted")
async def reconstruct_visual_assisted(
    file: UploadFile = File(...),
    damage_threshold: float = Form(DEFAULT_DAMAGE_SEGMENTATION_THRESHOLD),
    damage_min_area: int = Form(DEFAULT_DAMAGE_SEGMENTATION_MIN_AREA),
    guide_threshold: float = Form(DEFAULT_SEGMENTATION_THRESHOLD),
    guide_min_area: int = Form(DEFAULT_SEGMENTATION_MIN_AREA),
    guide_line_width: int = Form(DEFAULT_SEGMENTATION_LINE_WIDTH),
    include_previews: bool = Form(True),
    save_png: bool = Form(True),
):
    """
    Pipeline visual asistido:
    1. U-Net PyTorch v3 detecta dano.
    2. LaMa rellena solo textura de roca.
    3. El modelo Keras genera la guia del trazo.
    4. La guia se limita al dano y se oscurece para simular surco grabado.
    """
    global SEGMENTATION_MODEL, LAMA_MODEL

    if not (0.0 < damage_threshold < 1.0):
        raise HTTPException(status_code=400, detail="damage_threshold debe estar en (0, 1)")
    if not (0 < damage_min_area <= 50000):
        raise HTTPException(status_code=400, detail="damage_min_area debe estar entre 1 y 50000")
    if not (0.0 < guide_threshold < 1.0):
        raise HTTPException(status_code=400, detail="guide_threshold debe estar en (0, 1)")
    if not (0 <= guide_min_area <= 50000):
        raise HTTPException(status_code=400, detail="guide_min_area debe estar entre 0 y 50000")
    if not (1 <= guide_line_width <= 25):
        raise HTTPException(status_code=400, detail="guide_line_width debe estar entre 1 y 25")

    if petroglyph is None:
        raise HTTPException(
            status_code=503,
            detail=(
                "La segmentacion no esta disponible porque faltan dependencias del modelo "
                f"({PETROGLYPH_IMPORT_ERROR})."
            ),
        )
    if reconstruir is None:
        raise HTTPException(
            status_code=503,
            detail=f"Reconstruccion no disponible: {RECONSTRUCTION_IMPORT_ERROR}",
        )
    if SEGMENTATION_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo Keras no cargado")
    if LAMA_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo LaMa no cargado")
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Debes enviar un archivo de imagen valido")

    content = await file.read()
    if not content:
        raise HTTPException(status_code=400, detail="La imagen enviada esta vacia")

    np_buffer = np.frombuffer(content, np.uint8)
    img_bgr = petroglyph.cv2.imdecode(np_buffer, petroglyph.cv2.IMREAD_COLOR)
    if img_bgr is None:
        raise HTTPException(status_code=400, detail="No se pudo leer la imagen enviada")

    damage_model, damage_device = ensure_pytorch_damage_model()
    try:
        result = reconstruir.reconstruct_visual_assisted(
            SEGMENTATION_MODEL,
            LAMA_MODEL,
            damage_model,
            damage_device,
            img_bgr,
            damage_threshold=damage_threshold,
            damage_min_area=damage_min_area,
            guide_threshold=guide_threshold,
            guide_min_area=guide_min_area,
            guide_line_width=guide_line_width,
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"No se pudo ejecutar el pipeline asistido: {exc}") from exc

    output_paths = None
    if save_png:
        stem = Path(file.filename or "petroglifo").stem
        output_paths = reconstruir.save_visual_assisted_outputs(
            VISUAL_ASSISTED_OUTPUT_DIR,
            stem,
            result["original_rgb"],
            result["damage_probability"],
            result["damage_mask"],
            result["lama_rgb"],
            result["guide_mask"],
            result["missing_stroke"],
            result["fused_rgb"],
        )

    response: dict = {
        "filename": file.filename,
        "damage_threshold": float(damage_threshold),
        "damage_min_area": int(damage_min_area),
        "guide_threshold": float(guide_threshold),
        "guide_min_area": int(guide_min_area),
        "guide_line_width": int(guide_line_width),
        "damage_pixel_count": int(result["damage_pixel_count"]),
        "guide_pixel_count": int(result["guide_pixel_count"]),
        "selected_guide_threshold": float(result["selected_guide_threshold"]),
        "selected_guide_strategy": result["selected_guide_strategy"],
        "guide_metrics": result["guide_metrics"],
        "final_image": array_to_b64(result["fused_rgb"]),
        "fused_image": array_to_b64(result["fused_rgb"]),
        "lama_image": array_to_b64(result["lama_rgb"]),
        "damage_mask_image": grayscale_to_b64(result["damage_mask"]),
        "guide_mask_image": grayscale_to_b64(result["guide_mask"]),
        "missing_stroke_image": grayscale_to_b64(result["missing_stroke"]),
    }

    if include_previews:
        response.update(
            {
                "original_image": array_to_b64(result["original_rgb"]),
                "damage_probability_image": grayscale_to_b64(
                    np.clip(result["damage_probability"] * 255.0, 0, 255).astype(np.uint8)
                ),
                "guide_probability_image": grayscale_to_b64(
                    np.clip(result["guide_probability"] * 255.0, 0, 255).astype(np.uint8)
                ),
                "guide_base_mask_image": grayscale_to_b64(result["guide_mask_base"]),
            }
        )

    if output_paths is not None:
        response["saved_paths"] = {key: str(path) for key, path in output_paths.items()}

    return response
