# Generated by GitHub Copilot
import base64
import io
import warnings

import PIL.Image
import numpy as np
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response

warnings.filterwarnings("ignore")

app = FastAPI()

origins = [
    "http://localhost:5173",
    "http://localhost:5174",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

SEGMENTATION_MODEL = None
LAMA_MODEL = None
PETROGLYPH_IMPORT_ERROR = None
petroglyph = None
reconstruir = None
RECONSTRUCTION_IMPORT_ERROR = None

DEFAULT_SEGMENTATION_THRESHOLD = 0.5
DEFAULT_SEGMENTATION_MIN_AREA = 150
DEFAULT_SEGMENTATION_LINE_WIDTH = 2

try:
    import segmentar_petroglifo as petroglyph  # type: ignore[import-not-found]
except Exception as exc:
    PETROGLYPH_IMPORT_ERROR = exc
    petroglyph = None
else:
    DEFAULT_SEGMENTATION_THRESHOLD = petroglyph.DEFAULT_THRESHOLD
    DEFAULT_SEGMENTATION_MIN_AREA = petroglyph.DEFAULT_MIN_AREA
    DEFAULT_SEGMENTATION_LINE_WIDTH = petroglyph.DEFAULT_LINE_WIDTH

try:
    import reconstruir_petroglifo as reconstruir  # type: ignore[import-not-found]
except Exception as exc:
    RECONSTRUCTION_IMPORT_ERROR = exc
    reconstruir = None

def pil_to_b64(pil_img: PIL.Image.Image) -> str:
    buf = io.BytesIO()
    pil_img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode()


def array_to_b64(image_array: np.ndarray) -> str:
    pil_img = PIL.Image.fromarray(image_array)
    return pil_to_b64(pil_img)


def grayscale_to_b64(image_array: np.ndarray) -> str:
    pil_img = PIL.Image.fromarray(image_array.astype(np.uint8), mode="L")
    return pil_to_b64(pil_img)


def build_segmentation_status(metrics: dict, strategy: str) -> str:
    warnings = set(metrics.get("warnings", []))
    if "mask_empty" in warnings or "mask_too_small" in warnings:
        return "weak_segmentation"
    if "mask_too_large" in warnings:
        return "oversegmented"
    if strategy == "refined":
        return "refined_mask"
    return "ok"


@app.on_event("startup")
async def startup_event():
    global SEGMENTATION_MODEL, LAMA_MODEL

    if petroglyph is None:
        print(f"Segmentacion deshabilitada: {PETROGLYPH_IMPORT_ERROR}")
        return

    # --- Modelo Keras de segmentación (U-Net) ---
    segmentation_model_path = str(petroglyph.MODEL_PATH)
    print(f"Cargando modelo Keras (segmentación) desde {segmentation_model_path} ...")
    try:
        SEGMENTATION_MODEL = petroglyph.load_model(
            segmentation_model_path,
            custom_objects={
                "bce_dice_loss": petroglyph.bce_dice_loss,
                "dice_coefficient": petroglyph.dice_coefficient,
                "iou_score": petroglyph.iou_score,
            },
        )
        print("Modelo Keras cargado correctamente.")
    except Exception as e:
        print(f"Error cargando modelo Keras: {e}")

    # --- Modelo LaMa (inpainting con pérdida adversarial) ---
    if reconstruir is None:
        print(f"LaMa deshabilitado: {RECONSTRUCTION_IMPORT_ERROR}")
        return

    lama_model_path = reconstruir.DEFAULT_LAMA_MODEL_PATH
    print(f"Cargando modelo LaMa desde '{lama_model_path}' (fallback: pesos genéricos) ...")
    try:
        LAMA_MODEL = reconstruir.load_lama_model(model_path=lama_model_path)
        print("Modelo LaMa cargado correctamente.")
    except Exception as e:
        print(f"Error cargando modelo LaMa: {e}")


@app.post("/segmentPetroglyph")
async def segment_petroglyph(
    file: UploadFile = File(...),
    threshold: float = Form(DEFAULT_SEGMENTATION_THRESHOLD),
    min_area: int = Form(DEFAULT_SEGMENTATION_MIN_AREA),
    line_width: int = Form(DEFAULT_SEGMENTATION_LINE_WIDTH),
    include_previews: bool = Form(True),
):
    global SEGMENTATION_MODEL

    if petroglyph is None:
        raise HTTPException(
            status_code=503,
            detail=(
                "La segmentacion no esta disponible porque faltan dependencias del modelo "
                f"({PETROGLYPH_IMPORT_ERROR})."
            ),
        )

    if SEGMENTATION_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo de segmentacion no cargado")

    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Debes enviar un archivo de imagen valido")

    content = await file.read()
    if not content:
        raise HTTPException(status_code=400, detail="La imagen enviada esta vacia")

    np_buffer = np.frombuffer(content, np.uint8)
    img_bgr = petroglyph.cv2.imdecode(np_buffer, petroglyph.cv2.IMREAD_COLOR)
    if img_bgr is None:
        raise HTTPException(status_code=400, detail="No se pudo leer la imagen enviada")

    img_pre = petroglyph.preprocess(img_bgr)
    probability = petroglyph.predict_tta(SEGMENTATION_MODEL, img_pre)

    selected_mask = petroglyph.select_best_mask(probability, threshold, min_area)
    filled_mask = selected_mask["mask"]
    line_mask = petroglyph.adelgazar_mascara(filled_mask, grosor=line_width)
    metrics = selected_mask["metrics"]

    original_rgb = petroglyph.cv2.cvtColor(
        petroglyph.cv2.resize(img_bgr, (petroglyph.IMG_SIZE, petroglyph.IMG_SIZE), interpolation=petroglyph.cv2.INTER_AREA),
        petroglyph.cv2.COLOR_BGR2RGB,
    )
    background_rgb, background_name = petroglyph.choose_background(None)
    rendered_rgb = petroglyph.render_petroglyph(background_rgb, filled_mask)

    area_percent = float(metrics["area_percent"])
    segmentation_status = build_segmentation_status(metrics, str(selected_mask["strategy"]))

    response = {
        "filename": file.filename,
        "background_name": background_name,
        "threshold": threshold,
        "min_area": min_area,
        "line_width": line_width,
        "area_percent": round(area_percent, 2),
        "segmentation_status": segmentation_status,
        "selected_threshold": float(selected_mask["threshold"]),
        "selected_strategy": str(selected_mask["strategy"]),
        "validation_score": round(float(metrics["score"]), 2),
        "validation_warnings": list(metrics["warnings"]),
        "component_count": int(metrics["component_count"]),
        "size": {
            "width": petroglyph.IMG_SIZE,
            "height": petroglyph.IMG_SIZE,
        },
        "result_image": array_to_b64(rendered_rgb),
        "background_image": array_to_b64(background_rgb),
        "mask_image": grayscale_to_b64(filled_mask),
    }

    if include_previews:
        probability_img = np.clip(probability * 255.0, 0, 255).astype(np.uint8)
        response.update(
            {
                "original_image": array_to_b64(original_rgb),
                "probability_image": grayscale_to_b64(probability_img),
                "line_image": grayscale_to_b64(line_mask),
            }
        )

    return response


# ---------------------------------------------------------------------------
# Endpoints de reconstrucción
# Compatible con el agente A5 del sistema multiagente BackendPetroglifos
# ---------------------------------------------------------------------------

@app.post(
    "/reconstruct",
    summary="Reconstrucción de petroglifo (salida imagen PNG)",
    description=(
        "Recibe una imagen de un petroglifo deteriorado y devuelve la imagen "
        "reconstruida como PNG binario. "
        "Compatible con el agente A5 del sistema multiagente BackendPetroglifos "
        "(settings.gan_api_url)."
    ),
    response_class=Response,
)
async def reconstruct_petroglyph(
    image: UploadFile = File(...),
    threshold: float = Form(DEFAULT_SEGMENTATION_THRESHOLD),
    min_area: int = Form(DEFAULT_SEGMENTATION_MIN_AREA),
):
    """
    Pipeline de reconstrucción Keras + LaMa:
    1. Modelo Keras: segmentación TTA → mapa de probabilidad.
    2. Detección de surcos erosionados / zonas dañadas.
    3. LaMa GAN: inpainting generativo en zonas dañadas.
    4. Modelo Keras: re-segmentación post-inpainting.
    5. Renderizado sobre fondo pétreo con efecto de bajo relieve.

    Devuelve la imagen PNG de la reconstrucción como bytes crudos.
    Compatible con el agente A5 (settings.gan_api_url).

    Security note: threshold y min_area se validan contra rangos seguros.
    """
    global SEGMENTATION_MODEL, LAMA_MODEL

    if not (0.0 < threshold < 1.0):
        raise HTTPException(status_code=400, detail="threshold debe estar en (0, 1)")
    if not (0 <= min_area <= 50000):
        raise HTTPException(status_code=400, detail="min_area debe estar entre 0 y 50000")

    if reconstruir is None:
        raise HTTPException(
            status_code=503,
            detail=f"Reconstruccion no disponible: {RECONSTRUCTION_IMPORT_ERROR}",
        )
    if SEGMENTATION_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo Keras no cargado")
    if LAMA_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo LaMa no cargado")
    if not image.content_type or not image.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Debes enviar un archivo de imagen valido")

    content = await image.read()
    if not content:
        raise HTTPException(status_code=400, detail="La imagen enviada esta vacia")

    np_buffer = np.frombuffer(content, np.uint8)
    img_bgr = petroglyph.cv2.imdecode(np_buffer, petroglyph.cv2.IMREAD_COLOR)
    if img_bgr is None:
        raise HTTPException(status_code=400, detail="No se pudo leer la imagen enviada")

    result = reconstruir.reconstruct_petroglyph(
        SEGMENTATION_MODEL,
        LAMA_MODEL,
        img_bgr,
        threshold=threshold,
        min_area=min_area,
    )

    rendered = result["rendered_rgb"]
    pil_img = PIL.Image.fromarray(rendered)
    buf = io.BytesIO()
    pil_img.save(buf, format="PNG")
    buf.seek(0)
    return Response(content=buf.getvalue(), media_type="image/png")


@app.post(
    "/reconstructFull",
    summary="Reconstrucción de petroglifo (salida JSON con todas las etapas)",
    description=(
        "Igual que /reconstruct pero devuelve un JSON con imágenes codificadas en "
        "base-64 para cada etapa del pipeline (original, inpainting, máscara de "
        "daño, máscara final, probabilidad y resultado)."
    ),
)
async def reconstruct_petroglyph_full(
    file: UploadFile = File(...),
    threshold: float = Form(DEFAULT_SEGMENTATION_THRESHOLD),
    min_area: int = Form(DEFAULT_SEGMENTATION_MIN_AREA),
    line_width: int = Form(DEFAULT_SEGMENTATION_LINE_WIDTH),
    include_previews: bool = Form(True),
):
    """
    Devuelve todas las etapas del pipeline Keras + LaMa en base64.

    Campos del JSON:
    - ``result_image``             : reconstrucción final sobre fondo pétreo
    - ``inpainted_image``          : imagen tras inpainting LaMa
    - ``mask_image``               : máscara binaria final del petroglifo
    - ``damage_mask_image``        : máscara de zonas reconstruidas por LaMa
    - ``background_image``         : fondo pétreo utilizado
    - ``original_image``           : imagen original (si include_previews)
    - ``probability_image``        : mapa de probabilidad Keras (si include_previews)
    - ``probability_merged_image`` : mapa combinado post-LaMa (si include_previews)
    - ``line_image``               : esqueleto del petroglifo (si include_previews)
    - Métricas, umbrales y estadísticas del daño detectado.

    Security note: threshold y min_area se validan contra rangos seguros.
    """
    global SEGMENTATION_MODEL, LAMA_MODEL

    if not (0.0 < threshold < 1.0):
        raise HTTPException(status_code=400, detail="threshold debe estar en (0, 1)")
    if not (0 <= min_area <= 50000):
        raise HTTPException(status_code=400, detail="min_area debe estar entre 0 y 50000")

    if reconstruir is None:
        raise HTTPException(
            status_code=503,
            detail=f"Reconstruccion no disponible: {RECONSTRUCTION_IMPORT_ERROR}",
        )
    if SEGMENTATION_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo Keras no cargado")
    if LAMA_MODEL is None:
        raise HTTPException(status_code=500, detail="Modelo LaMa no cargado")
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Debes enviar un archivo de imagen valido")

    content = await file.read()
    if not content:
        raise HTTPException(status_code=400, detail="La imagen enviada esta vacia")

    np_buffer = np.frombuffer(content, np.uint8)
    img_bgr = petroglyph.cv2.imdecode(np_buffer, petroglyph.cv2.IMREAD_COLOR)
    if img_bgr is None:
        raise HTTPException(status_code=400, detail="No se pudo leer la imagen enviada")

    result = reconstruir.reconstruct_petroglyph(
        SEGMENTATION_MODEL,
        LAMA_MODEL,
        img_bgr,
        threshold=threshold,
        min_area=min_area,
    )

    metrics = result["metrics"]
    damage_count = int(result["damage_pixel_count"])
    total_pixels = petroglyph.IMG_SIZE * petroglyph.IMG_SIZE
    damage_percent = round(damage_count / total_pixels * 100.0, 2)

    response: dict = {
        "filename": file.filename,
        "background_name": result["background_name"],
        "threshold": threshold,
        "min_area": min_area,
        "line_width": line_width,
        "area_percent": round(float(metrics["area_percent"]), 2),
        "damage_pixel_count": damage_count,
        "damage_percent": damage_percent,
        "selected_threshold": result["selected_threshold"],
        "selected_strategy": result["selected_strategy"],
        "validation_score": round(float(metrics["score"]), 2),
        "validation_warnings": list(metrics["warnings"]),
        "component_count": int(metrics["component_count"]),
        "size": {
            "width": petroglyph.IMG_SIZE,
            "height": petroglyph.IMG_SIZE,
        },
        "result_image": array_to_b64(result["rendered_rgb"]),
        "inpainted_image": array_to_b64(result["inpainted_rgb"]),
        "mask_image": grayscale_to_b64(result["filled_mask"]),
        "damage_mask_image": grayscale_to_b64(result["damage_mask"]),
        "background_image": array_to_b64(
            petroglyph.choose_background(None)[0]
        ),
    }

    if include_previews:
        prob_img = np.clip(result["probability"] * 255.0, 0, 255).astype(np.uint8)
        prob_merged_img = np.clip(
            result["probability_merged"] * 255.0, 0, 255
        ).astype(np.uint8)
        response.update(
            {
                "original_image": array_to_b64(result["original_rgb"]),
                "probability_image": grayscale_to_b64(prob_img),
                "probability_merged_image": grayscale_to_b64(prob_merged_img),
                "line_image": grayscale_to_b64(result["line_mask"]),
            }
        )

    return response
